name: my first workflow

on: push

jobs:  
    myfirstjob:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message
              run: echo "my first job"
            - name: List files
              run: ls
            - name: Read file
              run: cat README.md  
