name: nodejs build and test

on:
  push:
    branches:
      - main
      
jobs:
  mynodejsjob:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install dep build and test
        run: |
         npm install -g npm@latest
         npm install
         npm run build 
         npm test
         echo "Build and tests completed successfully!"


