name: Node.js Build and Test

on:
  push:
    branches:
      - main

jobs:
  mynodejsjob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies, build, and test
        run: |
          # Update npm to a version compatible with Node.js 14
          npm install -g npm@6

          # Install project dependencies
          npm install

          # Build the project
          npm run build

          # Run tests
          npm test

          # Display success message
          echo "Build and tests completed successfully!"
